In [ ]:
# In this project we are going to learn about the LSTM architecture to build an Chatbot about predict-
# ing the sequence of word
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
text="""Grit is a unique combination of passion and perseverance, more important than talent in achieving long-term success.
 While talent matters, effort is crucial as it factors in twice: it builds skill and makes skill productive. People with grit focus on long-term goals and maintain determination despite failures and setbacks.
Passion is not something innate but develops through discovery, practice, and a lifetime of refinement. It involves caring deeply about a singular, top-level goal that gives meaning and direction to all other goals. Enthusiasm is common, but sustained commitment is rare. Grit requires working on something you deeply care about over a long period, staying loyal to the goal through challenges.
Deliberate practice is a hallmark of grit. It involves setting stretch goals, focusing on areas of weakness, seeking immediate feedback, and refining skills through repetition. Experts practice differently than novices, devoting thousands of hours to deliberate improvement. Flow, a state of effortless focus, is an enjoyable complement to deliberate practice but typically occurs during performance rather than preparation.
A growth mindset fuels grit by fostering the belief that abilities can improve with effort. Optimistic self-talk and resilience in the face of adversity are key components of grit. Gritty people view setbacks as temporary and specific rather than permanent and pervasive. They believe in their capacity to overcome challenges through consistent effort.
Purpose is a critical element of grit, connecting personal goals to contributions that benefit others. People with grit often see their work as meaningful beyond themselves, enhancing motivation. Purpose can be cultivated by reflecting on how one’s work helps others, aligning tasks with core values, and finding inspiration in role models.
Grit also thrives in environments that support it. A gritty culture promotes values of perseverance, hard work, and dedication. Joining such a culture can help internalize these values, reinforcing grit as a personal trait. Leaders can foster grit in organizations by setting examples and establishing norms that encourage passion and persistence.
Teaching grit to children involves encouraging them to pursue long-term interests and stick with activities for more than a year. Overbearing parenting erodes intrinsic motivation, while supportive environments help kids discover passions. Extracurricular activities, pursued consistently, build grit and correlate with greater success in adulthood.
Effort over time is the defining characteristic of grit. Many people quit too early or shift focus before reaching their potential. Grit is about staying the course, even when progress is slow or results are not immediate. It requires commitment to a singular life philosophy, with lower-level goals serving as stepping stones to the ultimate aim.
Angela Duckworth emphasizes that gritty individuals make decisions aligned with their identity and long-term aspirations. They prioritize goals that align with their ultimate concerns and are willing to adjust lower-level goals if needed. Grit grows with maturity, as individuals learn from experiences, adapt to challenges, and solidify their sense of purpose.
Ultimately, grit enables people to achieve extraordinary things through consistent effort and a refusal to give up. It is a skill that can be cultivated, strengthened, and applied to all areas of life, providing a roadmap for success through passion and perseverance.
"""

In [ ]:
tokenizer=Tokenizer()


In [ ]:
tokenizer.fit_on_texts([text])
print(tokenizer.word_index)
vocab_size=len(tokenizer.word_index)+1
print(vocab_size)


{'and': 1, 'grit': 2, 'a': 3, 'to': 4, 'of': 5, 'is': 6, 'with': 7, 'in': 8, 'that': 9, 'it': 10, 'goals': 11, 'as': 12, 'through': 13, 'the': 14, 'their': 15, 'than': 16, 'long': 17, 'effort': 18, 'people': 19, 'can': 20, 'passion': 21, 'term': 22, 'on': 23, 'practice': 24, 'perseverance': 25, 'success': 26, 'skill': 27, 'focus': 28, 'but': 29, 'involves': 30, 'about': 31, 'level': 32, 'challenges': 33, 'deliberate': 34, 'by': 35, 'are': 36, 'gritty': 37, 'purpose': 38, 'work': 39, 'values': 40, 'more': 41, 'talent': 42, 'while': 43, 'setbacks': 44, 'not': 45, 'something': 46, 'deeply': 47, 'singular': 48, 'goal': 49, 'all': 50, 'commitment': 51, 'requires': 52, 'over': 53, 'staying': 54, 'setting': 55, 'areas': 56, 'immediate': 57, 'rather': 58, 'they': 59, 'consistent': 60, 'personal': 61, 'others': 62, 'motivation': 63, 'be': 64, 'cultivated': 65, 'environments': 66, 'culture': 67, 'help': 68, 'activities': 69, 'for': 70, 'or': 71, 'life': 72, 'lower': 73, 'ultimate': 74, 'individu

In [ ]:
input_seq=[]
for line in text.split('.'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_seq.append(n_gram_sequence)
print(input_seq)

[[2, 6], [2, 6, 3], [2, 6, 3, 76], [2, 6, 3, 76, 77], [2, 6, 3, 76, 77, 5], [2, 6, 3, 76, 77, 5, 21], [2, 6, 3, 76, 77, 5, 21, 1], [2, 6, 3, 76, 77, 5, 21, 1, 25], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78, 16], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78, 16, 42], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78, 16, 42, 8], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78, 16, 42, 8, 79], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78, 16, 42, 8, 79, 17], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78, 16, 42, 8, 79, 17, 22], [2, 6, 3, 76, 77, 5, 21, 1, 25, 41, 78, 16, 42, 8, 79, 17, 22, 26], [43, 42], [43, 42, 80], [43, 42, 80, 18], [43, 42, 80, 18, 6], [43, 42, 80, 18, 6, 81], [43, 42, 80, 18, 6, 81, 12], [43, 42, 80, 18, 6, 81, 12, 10], [43, 42, 80, 18, 6, 81, 12, 10, 82], [43, 42, 80, 18, 6, 81, 12, 10, 82, 8], [43, 42, 80, 18, 6, 81, 12, 10, 82, 8, 83], [43, 42, 80, 18, 6, 81, 12, 10, 82, 8, 83, 10], [43, 42, 80, 18, 6, 81, 12, 10, 82, 8, 83, 10

In [ ]:
max_len=max([len(x) for x in input_seq])

In [ ]:
print(max_len)

25


In [ ]:
padded_input_seq=pad_sequences(input_seq,maxlen=max_len,padding='pre')

In [ ]:
padded_input_seq

array([[ 0,  0,  0, ...,  0,  2,  6],
       [ 0,  0,  0, ...,  2,  6,  3],
       [ 0,  0,  0, ...,  6,  3, 76],
       ...,
       [ 0,  0, 10, ..., 26, 13, 21],
       [ 0, 10,  6, ..., 13, 21,  1],
       [10,  6,  3, ..., 21,  1, 25]], dtype=int32)

In [ ]:
X=padded_input_seq[:,:-1]

In [ ]:
X.shape

(491, 24)

In [ ]:
y=padded_input_seq[:,-1]

In [ ]:
y.shape

(491, 283)

In [ ]:
y


array([  6,   3,  76,  77,   5,  21,   1,  25,  41,  78,  16,  42,   8,
        79,  17,  22,  26,  42,  80,  18,   6,  81,  12,  10,  82,   8,
        83,  10,  84,  27,   1,  85,  27,  86,   7,   2,  28,  23,  17,
        22,  11,   1,  87,  88,  89,  90,   1,  44,   6,  45,  46,  91,
        29,  92,  13,  93,  24,   1,   3,  94,   5,  95,  30,  96,  47,
        31,   3,  48,  97,  32,  49,   9,  98,  99,   1, 100,   4,  50,
       101,  11,   6, 103,  29, 104,  51,   6, 105,  52, 106,  23,  46,
       107,  47, 108,  31,  53,   3,  17, 109,  54, 110,   4,  14,  49,
        13,  33,  24,   6,   3, 111,   5,   2,  30,  55, 112,  11, 113,
        23,  56,   5, 114, 115,  57, 116,   1, 117, 118,  13, 119,  24,
       121,  16, 122, 123, 124,   5, 125,   4,  34, 126,   3, 128,   5,
       129,  28,   6, 130, 131, 132,   4,  34,  24,  29, 133, 134, 135,
       136,  58,  16, 137, 138, 139, 140,   2,  35, 141,  14, 142,   9,
       143,  20, 144,   7,  18, 146, 147,   1, 148,   8,  14, 14

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=283)

In [ ]:
y[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=283, output_dim=100))
model.add(LSTM(128, return_sequences=False))
model.add(Dense(283, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - accuracy: 0.0135 - loss: 5.6427
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.0182 - loss: 5.4900
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.0499 - loss: 5.3078
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.0491 - loss: 5.2839
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - accuracy: 0.0504 - loss: 5.1648
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.0586 - loss: 5.1015
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.0567 - loss: 5.0108
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.0623 - loss: 5.0138
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.0974 - loss: 4.7818
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.0738 - loss: 4.7912
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.0577 - loss: 4.7475
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step

In [ ]:
import time
text='while talent'
for i in range(20):
  tokenized_text=tokenizer.texts_to_sequences([text])
  padded_text=pad_sequences(tokenized_text,maxlen=max_len,padding='pre')
  position_of_softmax=np.argmax([model.predict(padded_text)])
  for word,index in tokenizer.word_index.items():
    if position_of_softmax==index:
      text=text+' '+word
      time.sleep(1)
      print(text)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
while talent matters
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
while talent matters effort
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
while talent matters effort is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
while talent matters effort is crucial
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
while talent matters effort is crucial as
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
while talent matters effort is crucial as it
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
while talent matters effort is crucial as it factors
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
while talent matters effort is crucial as it factors in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
while talent matters effort is crucial as it factors in twice
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
while talent matters effort is crucial as it factors in twice it
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
while talent matters effort is crucial as it factors in twice it builds
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
while talent matters effort is